version: "3.9"
services:
  #UI service
  front-end-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ui-container
    image: manage-users-ui:v1
    restart: unless-stopped
    ports:
      - '80:80'
    networks:
      - app-network
  #mock service
  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3000 -w db.json
    init: true
    ports:
      - "3000:3000"
    volumes:
      - ./mock-data/data:/data
    restart: unless-stopped
    networks:
      - app-network
networks:
  app-network:
    external: true
